spring:
  application:
    name: sbc-cms-api
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:15433/postgres
    username: postgres
    password: postgres
