## Criar usuarios normais

POST http://localhost:8080/usuarios
Content-Type: application/json

{
  "login": "joaquim",
  "nome": "Joaquim",
  "email": "YcJp4@example.com",
  "afiliacao": "afiliacao"
}

### Listar eventos

GET http://localhost:8080/eventos?page=0&size=10

### Obter um evento por ID

GET http://localhost:8080/eventos/2

### Criar um novo evento

POST http://localhost:8080/eventos
Content-Type: application/json

{
  "nome": "evento 1",
  "sigla": "EVT",
  "descricao": "descrição do evento 1"
}

### Alterar um evento

PUT http://localhost:8080/eventos/2
Content-Type: application/json

{
  "nome": "evento 2",
  "sigla": "EVT",
  "descricao": "descrição do evento 2"
}

### Excluir um evento

DELETE http://localhost:8080/eventos/1

### Listar edições

GET http://localhost:8080/eventos/2/edicoes

### Obter uma edição

GET http://localhost:8080/eventos/1/edicoes/1

### Criar uma edição

POST http://localhost:8080/eventos/1/edicoes
Content-Type: application/json

{
  "numero": 1,
  "ano": 2020,
  "dataInicial": "2020-01-01",
  "dataFinal": "2020-01-01",
  "cidade": "Cidade"
}

### Alterar uma edição

PUT http://localhost:8080/eventos/1/edicoes/1
Content-Type: application/json

{
  "numero": 1,
  "ano": 2024,
  "dataInicial": "2024-01-01",
  "dataFinal": "2024-01-01",
  "cidade": "Cidade"
}

### Excluir uma edição

DELETE http://localhost:8080/eventos/1/edicoes/1

###

POST http://localhost:8080/eventos/1/edicoes/2/organizador
Content-Type: application/json

{
  "organizadorId": 1
}

### Listar espaços

GET http://localhost:8080/espacos

### Obter um espaço por ID

GET http://localhost:8080/espacos/1

### Criar um novo espaço

POST http://localhost:8080/espacos
Content-Type: application/json

{
  "nome": "nome",
  "localizacao": "localizacao",
  "capacidade": 20,
  "recursos": [
    "recurso 1",
    "recurso 2"
  ]
}

### Alterar um espaco

PUT http://localhost:8080/espacos/1
Content-Type: application/json

{
  "nome": "nome alterado",
  "localizacao": "localizacao alterada",
  "capacidade": 20,
  "recursos": [
    "recurso 1",
    "recurso 2"
  ]
}

### Excluir um espaco

DELETE http://localhost:8080/espacos/1

### Listar atividades

GET http://localhost:8080/eventos/1/edicoes/1/atividades

### Obter uma atividade

GET http://localhost:8080/eventos/1/edicoes/1/atividades/1

### Criar uma atividade

POST http://localhost:8080/eventos/1/edicoes/1/atividades
Content-Type: application/json

{
  "nome": "nome da atividade",
  "tipo": "DISTANCIA",
  "descricao": "descrição da atividade",
  "data": "2020-01-01",
  "horarioInicial": "08:00",
  "horarioFinal": "10:00",
  "localId": 1
}

### Alterar uma atividade

PUT http://localhost:8080/eventos/1/edicoes/1/atividades/1
Content-Type: application/json

{
  "nome": "nome da atividade alterada",
  "descricao": "descrição da atividade alterada",
  "data": "2020-01-01",
  "horarioicial": "08:00",
  "horarioFinal": "10:00",
  "localId": 1
}

### Excluir uma atividade

DELETE http://localhost:8080/eventos/1/edicoes/1/atividades/1

### Favoritar

POST http://localhost:8080/usuarios/1/favoritar
Content-Type: application/json

{
  "atividadeId": 1
}

### Desfavoritar

POST http://localhost:8080/usuarios/1/desfavoritar
Content-Type: application/json

{
  "atividadeId": 1
}
